# Generated by Django 4.2.6 on 2023-10-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_article_is_published_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preview',
        ),
    ]
